---
- hosts: webservers
  become: yes
  tasks:
    - name: Actualizar cache de apt
      apt:
        update_cache: yes

    - name: Instalar Apache
      apt:
        name: apache2
        state: present

    - name: Instalar Cowsay
      apt:
        name: cowsay
        state: present

    - name: Crear un archivo
      copy:
        dest: /home/vagrant/hola_mundo.txt
        content: "Hola Mundo desde Ansible"

    - name: Copiar archivos
      copy:
        src: /vagrant/archivo_fuente.txt
        dest: /home/vagrant/archivo_destino.txt

    - name: Crear carpetas
      file:
        path: /home/vagrant/carpeta_ansible
        state: directory

    - name: Iniciar el servicio de Apache
      service:
        name: apache2
        state: started

    - name: Agregar un usuario
      user:
        name: ansible_user
        state: present

    - name: Ejecutar un script
      command: /home/vagrant/script.sh
